language: python
python:
  - 2.7.9

install: 
  - wget https://github.com/Worldev/Granota/raw/tools/testbot.py
  - pip install coveralls

script: 
  - python testbot.py
  - coverage run testbot.py
  
after_success:
  coveralls
